@startuml
abstract class Arg {
	+Default    : //any//
	+IsOptional : bool = false

	+Combine( args : list<Arg> ) : Arg

	+UsageShort()                : string
	+UsageLong()                 : string
	+Completes( str : string )   : table
	+Parse( str : string )       : //any//, string

	+Serialize()                 : string
	+Deserialize( serial : str )
}

class ArgNum {
	+Default : number = 0
	+Min     : number?
	+Max     : number?
	+RoundTo : number?
}

class ArgTime {
}

class ArgString {
	+RestrictToCompletes : bool = false
	+StrCompletes : table?
}

class ArgPlayer {
	+RestrictTarget : string?
	+AllowOfflineID : bool
}

Command "1" *-- "*" Arg

Arg <|-- ArgNum
ArgTime <|-- ArgNum
Arg <|-- ArgString
Arg <|-- ArgPlayer
@enduml
